### ISSUE TITLE
I want Topo lines on the main map

### ISSUE THREAD

**Issue by bricepollock** [bricepollock/canyoneer#6]
Really wish MapKit had this. If we move to mapbox for the general map to get topo lines we'll have to implement a different map download pattern for tiles instead of individual canyons like we have today.

**Comment by lucaswoj** [comment]
As part of https://github.com/OpenCanyon/api/issues/21 I am going to start putting together a custom Mapbox style for our data

**Comment by bricepollock** [comment]
As part of the conversion to https://github.com/CanyoneerApp we will need to move towards the Mapbox tiles so we can show topo lines on the map again.
